-- Civil & Commercial Code Learning Platform - Schema
CREATE TABLE IF NOT EXISTS sections (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, title_en TEXT, section_type TEXT NOT NULL, section_number TEXT, parent_id INTEGER REFERENCES sections(id) ON DELETE CASCADE, sort_order INTEGER DEFAULT 0, summary TEXT, detail TEXT, penalty TEXT, keywords TEXT, created_at TEXT DEFAULT (datetime('now')), updated_at TEXT DEFAULT (datetime('now')));
CREATE INDEX IF NOT EXISTS idx_sections_parent ON sections(parent_id);
CREATE INDEX IF NOT EXISTS idx_sections_type ON sections(section_type);
CREATE TABLE IF NOT EXISTS mindmap_nodes (id INTEGER PRIMARY KEY AUTOINCREMENT, section_id INTEGER REFERENCES sections(id) ON DELETE CASCADE, label TEXT NOT NULL, color TEXT DEFAULT 'teal', icon TEXT, x_pos REAL DEFAULT 0, y_pos REAL DEFAULT 0, width REAL DEFAULT 200, height REAL DEFAULT 60, parent_node_id INTEGER REFERENCES mindmap_nodes(id) ON DELETE SET NULL, is_collapsed INTEGER DEFAULT 0, created_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS node_notes (id INTEGER PRIMARY KEY AUTOINCREMENT, node_id INTEGER NOT NULL REFERENCES mindmap_nodes(id) ON DELETE CASCADE, content TEXT NOT NULL, note_type TEXT DEFAULT 'personal', is_pinned INTEGER DEFAULT 0, created_at TEXT DEFAULT (datetime('now')), updated_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS videos (id INTEGER PRIMARY KEY AUTOINCREMENT, youtube_id TEXT NOT NULL UNIQUE, title TEXT NOT NULL, channel TEXT, thumbnail_url TEXT, duration_sec INTEGER, description TEXT, quality_rating INTEGER DEFAULT 0, is_favorite INTEGER DEFAULT 0, watch_status TEXT DEFAULT 'unwatched', added_at TEXT DEFAULT (datetime('now')), watched_at TEXT);
CREATE TABLE IF NOT EXISTS tags (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL UNIQUE, category TEXT DEFAULT 'topic', color TEXT DEFAULT '#888', created_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS video_tags (video_id INTEGER NOT NULL REFERENCES videos(id) ON DELETE CASCADE, tag_id INTEGER NOT NULL REFERENCES tags(id) ON DELETE CASCADE, PRIMARY KEY (video_id, tag_id));
CREATE TABLE IF NOT EXISTS node_videos (node_id INTEGER NOT NULL REFERENCES mindmap_nodes(id) ON DELETE CASCADE, video_id INTEGER NOT NULL REFERENCES videos(id) ON DELETE CASCADE, note TEXT, timestamp_sec INTEGER, PRIMARY KEY (node_id, video_id));
CREATE TABLE IF NOT EXISTS lecture_notes (id INTEGER PRIMARY KEY AUTOINCREMENT, section_id INTEGER REFERENCES sections(id) ON DELETE SET NULL, title TEXT NOT NULL, content TEXT NOT NULL, source TEXT, note_type TEXT DEFAULT 'summary', is_starred INTEGER DEFAULT 0, created_at TEXT DEFAULT (datetime('now')), updated_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS note_videos (note_id INTEGER NOT NULL REFERENCES lecture_notes(id) ON DELETE CASCADE, video_id INTEGER NOT NULL REFERENCES videos(id) ON DELETE CASCADE, PRIMARY KEY (note_id, video_id));
